//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string FullName { get; set; }
        public System.DateTime Dateofbirth { get; set; }
        public string Gender { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string Email { get; set; }
        public System.DateTime dateofreg { get; set; }
    }
}
